Notes (2023/11/30 | Coach: CJ | self directed learning)

## Error handling

### Kind of errors

- static error (i.e. bracket missing)
- runtime error
  - detected when program runs
  - attempting to call something that is not a function

### Catching runtime errors

### Throwing custom errors

Possible exceptions may be:

- trying to access a non existing network resource or local file
- trying to write to a full disk
- trying to navigate while offline
- trying to access a resource without having the right credentials to do so

### Example 1

templates/js/js-error-handling/20231130-js-error-handling1-calculator-solution

```js
console.clear();

const form = document.querySelector("form");
const output = form.querySelector("output");

const operations = {
  add: (a, b) => a + b,
  subtract: (a, b) => a - b,
  multiply: (a, b) => a * b,
  divide: (a, b) => {
    if (b === 0) {
      throw new Error("Cannot divide by zero!");
    }
    return a / b;
  },
};

// If the object above looks weird & confusing and you're
// unsure how it works, then take a look at a different
// way of constructing the above object:

// Arrow Functions:
// const add = (a,b) => a + b;
// const subtract = (a,b) => a - b;
// const multiply = (a,b) => a * b;
// const divide = (a,b) => {
//     if (b === 0) {
//       throw new Error("Cannot divide by zero!");
//     }
//     return a / b;
//   },

// Constructing the Object
// const operations = {
//   add,
//   subtract,
//   multiply,
//   divide,
// };

// You could also handle this by calling the functions
// individually as part of an if/else structure, etc.

form.addEventListener("submit", (event) => {
  event.preventDefault();
  const firstNumber = Number(event.target.firstNumber.value);
  const secondNumber = Number(event.target.secondNumber.value);
  const operation = event.target.operation.value;

  try {
    output.innerText = operations[operation](firstNumber, secondNumber);
    document.querySelector(".error").innerText = "";
  } catch (error) {
    console.log(error);
    console.error(error);
    // This isn't necessary. It's just to visualize the difference between console.log and console.error.
    output.innerText = "‚ùå";
    document.querySelector(".error").innerText = error.message;
  }
});
```

### Example 2

templates/js/js-error-handling/20231130-js-error-handling2-fetch-solution

```js
console.clear();

const userElement = document.querySelector(".user");
const errorElement = document.querySelector(".error");

async function loadUser(url) {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }

    const json = await response.json();
    const user = json.data;

    errorElement.textContent = "";

    userElement.innerHTML = `
    <h2>${user.first_name} ${user.last_name}</h2>
    <img alt="${user.first_name} ${user.last_name}" src="${user.avatar}"/>
    `;
  } catch (error) {
    errorElement.textContent = error.message;
    userElement.innerHTML = "No user data available.";
  }
}

document
  .querySelectorAll("button[data-url]")
  .forEach((button) =>
    button.addEventListener("click", (event) =>
      loadUser(event.target.dataset.url)
    )
  );
```
